import Box from "./styledComponents/Box";
import Button from "./styledComponents/Button";
import Form from "./styledComponents/Form";
import Link from "./styledComponents/Link";
import StateChanger from "./styledComponents/StateChanger";
import Wrapper from "./styledComponents/Wrapper";
import Input from "./styledComponents/Input";
import LoginBox from "./styledComponents/LoginBox";
import LoginWrapper from "./styledComponents/LoginWrapper";
import HeaderStyled from "./styledComponents/HeaderStyled";
import HeaderColumn from "./styledComponents/HeaderColumn";
import HeaderWrapper from "./styledComponents/HeaderWrapper";
import HeaderLink from "./styledComponents/HeaderLink";
import SearchInput from "./styledComponents/SearchInput";
import CenterColumn from "./styledComponents/CenterColumn";
import DarkButton from "./styledComponents/DarkButton";
import RedHeaderColumn from "./styledComponents/RedHeaderColumn";
import ModalButton from "./styledComponents/ModalButton";
import ModalColumn from "./styledComponents/ModalComlum";
import PopUp from "./styledComponents/PopUp";
import ModalInner from "./styledComponents/ModalInner";
import ModalOverlay from "./styledComponents/ModalOverlay";
import ModalWrapper from "./styledComponents/ModalWrapper";

export const BOX = Box;
export const BUTTOIN = Button;
export const LINK = Link;
export const FORM = Form;
export const STATE_CHANGER = StateChanger;
export const WRAPPER = Wrapper;
export const INPUT = Input;
export const LOGIN_BOX = LoginBox;
export const LOGIN_WRAPPER = LoginWrapper;
export const HEADER = HeaderStyled;
export const HEADER_COLUMN = HeaderColumn;
export const HEADER_WRAPPER = HeaderWrapper;
export const HEADER_LINK = HeaderLink;
export const SEARCH_INPUT = SearchInput;
export const CENTER_COLUMN = CenterColumn;
export const DARK_BUTTON = DarkButton;
export const RED_COLUMN = RedHeaderColumn;
export const MODAL_BUTTON = ModalButton;
export const MODAL_COLUMN = ModalColumn;
export const POP_UP = PopUp;
export const MODAL_OVERLAY = ModalOverlay;
export const MODAL_INNER = ModalInner;
export const MODAL_WRAPPER = ModalWrapper;
